export const CROPS = [
  {
    id: "acelga",
    emoji: "🥬",
    name: "Acelga",
    type: "Hortaliza de hoja",
    agua: "Media",
    riego: "Goteo / Gravedad",
    ciclo: "60–90 días",
    frecuencia: "Cada 3–4 días",
    dosis: "4–5 L/m²",
    fertilizacion: "NPK 20-10-10 al trasplante, urea a los 30 días",
    tip: "Sensible al exceso de agua. Riega por las mañanas para evitar hongos en las noches.",
    deficiencias: ["Nitrógeno: hojas amarillas pálidas en toda la planta", "Hierro: amarillamiento entre las nervaduras en hojas jóvenes"],
  },
  {
    id: "lechuga",
    emoji: "🥗",
    name: "Lechuga",
    type: "Hortaliza de hoja",
    agua: "Alta",
    riego: "Goteo",
    ciclo: "45–70 días",
    frecuencia: "Cada 2–3 días",
    dosis: "5–6 L/m²",
    fertilizacion: "NPK 12-24-12 al inicio, nitrógeno fraccionado cada 15 días",
    tip: "Requiere humedad constante sin encharcamiento. El estrés hídrico amarga las hojas.",
    deficiencias: ["Calcio: bordes de hojas quemados (tip burn)", "Nitrógeno: crecimiento lento, hojas pequeñas y amarillentas"],
  },
  {
    id: "tomate",
    emoji: "🍅",
    name: "Tomate",
    type: "Solanácea",
    agua: "Alta",
    riego: "Goteo",
    ciclo: "90–120 días",
    frecuencia: "Diario en verano",
    dosis: "6–8 L/m²",
    fertilizacion: "Alto en fósforo al inicio, potasio en fructificación",
    tip: "El estrés hídrico en floración reduce el cuajado. Riego uniforme evita el rajado del fruto.",
    deficiencias: ["Magnesio: amarillamiento internervial en hojas viejas", "Potasio: bordes de hojas quemados en hojas maduras"],
  },
  {
    id: "aji",
    emoji: "🌶️",
    name: "Ají",
    type: "Solanácea",
    agua: "Media",
    riego: "Goteo",
    ciclo: "90–150 días",
    frecuencia: "Cada 3–4 días",
    dosis: "4–5 L/m²",
    fertilizacion: "NPK equilibrado, más potasio en maduración para coloración",
    tip: "Tolera algo de sequía. Exceso de agua pudre las raíces y baja la pungencia del fruto.",
    deficiencias: ["Boro: flores caen sin cuajar, frutos deformes", "Zinc: hojas pequeñas con manchas cloróticas"],
  },
  {
    id: "cebolla",
    emoji: "🧅",
    name: "Cebolla",
    type: "Bulbosa",
    agua: "Media-alta",
    riego: "Surco / Goteo",
    ciclo: "120–150 días",
    frecuencia: "Cada 5–7 días",
    dosis: "5–6 L/m²",
    fertilizacion: "Fósforo al trasplante, nitrógeno hasta los 90 días, suspender después",
    tip: "Suspende el riego 2–3 semanas antes de la cosecha para que el bulbo madure y seque bien.",
    deficiencias: ["Azufre: hojas nuevas amarillas uniformes", "Nitrógeno: follaje pálido, bulbos pequeños"],
  },
  {
    id: "zanahoria",
    emoji: "🥕",
    name: "Zanahoria",
    type: "Raíz",
    agua: "Media",
    riego: "Aspersión / Surco",
    ciclo: "90–120 días",
    frecuencia: "Cada 4–5 días",
    dosis: "4–5 L/m²",
    fertilizacion: "Bajo en nitrógeno, alto en fósforo y potasio para engrosar la raíz",
    tip: "Suelo suelto y profundo sin piedras. El encharcamiento provoca bifurcación y pudrición de raíz.",
    deficiencias: ["Boro: raíces cortas y deformes, corazón café", "Potasio: follaje quemado, raíces pequeñas"],
  },
  {
    id: "espinaca",
    emoji: "🌿",
    name: "Espinaca",
    type: "Hortaliza de hoja",
    agua: "Media",
    riego: "Goteo",
    ciclo: "40–60 días",
    frecuencia: "Cada 3 días",
    dosis: "4 L/m²",
    fertilizacion: "Alto en nitrógeno para máxima producción de hojas verdes oscuras",
    tip: "Ciclo corto, ideal para sembrar entre filas de otros cultivos. Sensible al calor (florece precoz).",
    deficiencias: ["Nitrógeno: hojas pequeñas, amarillas pálidas", "Hierro: clorosis internervial en hojas jóvenes"],
  },
  {
    id: "pepino",
    emoji: "🥒",
    name: "Pepino",
    type: "Cucurbitácea",
    agua: "Alta",
    riego: "Goteo",
    ciclo: "55–70 días",
    frecuencia: "Diario en producción",
    dosis: "7–8 L/m²",
    fertilizacion: "NPK 15-15-15 al inicio, potasio alto en fructificación",
    tip: "Muy sensible al déficit hídrico: los frutos se tuercen o amargan. Riego constante y uniforme.",
    deficiencias: ["Calcio: pudrición apical del fruto", "Magnesio: amarillamiento entre nervaduras en hojas viejas"],
  },
  {
    id: "berenjena",
    emoji: "🍆",
    name: "Berenjena",
    type: "Solanácea",
    agua: "Media",
    riego: "Goteo",
    ciclo: "90–120 días",
    frecuencia: "Cada 3–4 días",
    dosis: "5–6 L/m²",
    fertilizacion: "Alto en nitrógeno al inicio, equilibrado en floración",
    tip: "Buen desempeño en el clima cálido de Lima. Riego uniforme evita el abortado de flores.",
    deficiencias: ["Nitrógeno: plantas débiles, frutos pequeños", "Potasio: bordes de hojas quemados"],
  },
  {
    id: "rabano",
    emoji: "🌱",
    name: "Rábano",
    type: "Raíz",
    agua: "Media",
    riego: "Surco",
    ciclo: "25–35 días",
    frecuencia: "Cada 3–4 días",
    dosis: "3–4 L/m²",
    fertilizacion: "Poco nitrógeno, fósforo y potasio para engordar la raíz",
    tip: "Cultivo rapidísimo. Ideal para aprovechar espacios vacíos entre otros cultivos más lentos.",
    deficiencias: ["Boro: raíces huecas, deformes", "Fósforo: raíces pequeñas, follaje verde oscuro azulado"],
  },
];
